---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-configmap-deployment
  labels:
    app: nginx-configmap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-configmap
  template:
    metadata:
      labels:
        app: nginx-configmap
    spec:
      containers:
      - name: nginx-configmap
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        env:
        - name: db
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: App
