---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secret-env-deployment
  labels:
    app: nginx-secret-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-secret-env
  template:
    metadata:
      labels:
        app: nginx-secret-env
    spec:
      containers:
      - name: nginx-secret-env
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
